use_frameworks!

target 'XDJVendor_Example', :exclusive => true do
  pod 'XDJVendor', :path => '../'
end

target 'XDJVendor_Tests', :exclusive => true do
  pod 'XDJVendor', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
